// related to auth
export const PARENT_REGISTER_REQUEST = 'PARENT_REGISTER_REQUEST'
export const PARENT_REGISTER_SUCCESS = 'PARENT_REGISTER_SUCCESS'
export const PARENT_REGISTER_FAIL = 'PARENT_REGISTER_FAIL'

export const PARENT_LOGIN_REQUEST = 'PARENT_LOGIN_REQUEST'
export const PARENT_LOGIN_SUCCESS = 'PARENT_LOGIN_SUCCESS'
export const PARENT_LOGIN_FAIL = 'PARENT_LOGIN_FAIL'

export const PARENT_LOGOUT = 'PARENT_LOGOUT'

export const PARENT_STUDENTS_UPDATE = 'PARENT_STUDENTS_UPDATE'

// add student (and delete addStudent)
export const PARENT_ADD_STUDENT_REQUEST = 'PARENT_ADD_STUDENT_REQUEST'
export const PARENT_ADD_STUDENT_SUCCESS = 'PARENT_ADD_STUDENT_SUCCESS'
export const PARENT_ADD_STUDENT_FAIL = 'PARENT_ADD_STUDENT_FAIL'
export const PARENT_ADD_STUDENT_DELETE = 'PARENT_ADD_STUDENT_DELETE'

// get marks (and delete marks)
export const PARENT_MARKS_REQUEST = 'PARENT_MARKS_REQUEST'
export const PARENT_MARKS_SUCCESS = 'PARENT_MARKS_SUCCESS'
export const PARENT_MARKS_FAIL = 'PARENT_MARKS_FAIL'
export const PARENT_MARKS_DELETE = 'PARENT_MARKS_DELETE'

// get truancys (and delete truancys)
export const PARENT_TRUANCYS_REQUEST = 'PARENT_TRUANCYS_REQUEST'
export const PARENT_TRUANCYS_SUCCESS = 'PARENT_TRUANCYS_SUCCESS'
export const PARENT_TRUANCYS_FAIL = 'PARENT_TRUANCYS_FAIL'
export const PARENT_TRUANCYS_DELETE = 'PARENT_TRUANCYS_DELETE'

// get average marks
export const PARENT_GET_AVERAGE_REQUEST = 'PARENT_GET_AVERAGE_REQUEST'
export const PARENT_GET_AVERAGE_SUCCESS = 'PARENT_GET_AVERAGE_SUCCESS'
export const PARENT_GET_AVERAGE_FAIL = 'PARENT_GET_AVERAGE_FAIL'

// get term marks
export const PARENT_GET_TERM_MARKS_REQUEST = 'PARENT_GET_TERM_MARKS_REQUEST'
export const PARENT_GET_TERM_MARKS_SUCCESS = 'PARENT_GET_TERM_MARKS_SUCCESS'
export const PARENT_GET_TERM_MARKS_FAIL = 'PARENT_GET_TERM_MARKS_FAIL'
