// related to auth
export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST'
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS'
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL'

export const STUDENT_UPDATE_GRADE = 'STUDENT_UPDATE_GRADE'
export const STUDENT_UPDATE_SUBJECT_LIST = 'STUDENT_UPDATE_SUBJECT_LIST'

export const STUDENT_LOGOUT = 'STUDENT_LOGOUT'

// get marks (and delete marks)
export const STUDENT_SUBJECT_MARKS_REQUEST = 'STUDENT_SUBJECT_MARKS_REQUEST'
export const STUDENT_SUBJECT_MARKS_SUCCESS = 'STUDENT_SUBJECT_MARKS_SUCCESS'
export const STUDENT_SUBJECT_MARKS_FAIL = 'STUDENT_SUBJECT_MARKS_FAIL'
export const STUDENT_SUBJECT_MARKS_DELETE = 'STUDENT_SUBJECT_MARKS_DELETE'

// get truancys (and delete marks)
export const STUDENT_SUBJECT_TRUANCYS_REQUEST =
  'STUDENT_SUBJECT_TRUANCYS_REQUEST'
export const STUDENT_SUBJECT_TRUANCYS_SUCCESS =
  'STUDENT_SUBJECT_TRUANCYS_SUCCESS'
export const STUDENT_SUBJECT_TRUANCYS_FAIL = 'STUDENT_SUBJECT_TRUANCYS_FAIL'
export const STUDENT_SUBJECT_TRUANCYS_DELETE = 'STUDENT_SUBJECT_TRUANCYS_DELETE'

// get average marks
export const STUDENT_GET_AVERAGE_REQUEST = 'STUDENT_GET_AVERAGE_REQUEST'
export const STUDENT_GET_AVERAGE_SUCCESS = 'STUDENT_GET_AVERAGE_SUCCESS'
export const STUDENT_GET_AVERAGE_FAIL = 'STUDENT_GET_AVERAGE_FAIL'

// get average marks
export const STUDENT_GET_TERM_MARKS_REQUEST = 'STUDENT_GET_TERM_MARKS_REQUEST'
export const STUDENT_GET_TERM_MARKS_SUCCESS = 'STUDENT_GET_TERM_MARKS_SUCCESS'
export const STUDENT_GET_TERM_MARKS_FAIL = 'STUDENT_GET_TERM_MARKS_FAIL'
