// teacher login
export const TEACHER_UPDATE = 'TEACHER_UPDATE'

export const TEACHER_READ_LS = 'TEACHER_READ_LS'

export const TEACHER_LOGOUT = 'TEACHER_LOGOUT'

// teacher homeroom
export const TEACHER_HOMEROOM_STUDENTS_REQUEST =
  'TEACHER_HOMEROOM_STUDENTS_REQUEST'
export const TEACHER_HOMEROOM_STUDENTS_SUCCESS =
  'TEACHER_HOMEROOM_STUDENTS_SUCCESS'
export const TEACHER_HOMEROOM_STUDENTS_FAIL =
  'TEACHER_HOMEROOM_STUDENTS_FAIL'
export const TEACHER_HOMEROOM_STUDENTS_DELETE =
  'TEACHER_HOMEROOM_STUDENTS_DELETE'

// teacher homeroom get average
export const TEACHER_HOMEROOM_AVERAGE_MARKS_REQUEST =
  'TEACHER_HOMEROOM_AVERAGE_MARKS_REQUEST'
export const TEACHER_HOMEROOM_AVERAGE_MARKS_SUCCESS =
  'TEACHER_HOMEROOM_AVERAGE_MARKS_SUCCESS'
export const TEACHER_HOMEROOM_AVERAGE_MARKS_FAIL =
  'TEACHER_HOMEROOM_AVERAGE_MARKS_FAIL'

// teacher homeroom get term marks
export const TEACHER_HOMEROOM_TERM_MARKS_REQUEST =
  'TEACHER_HOMEROOM_TERM_MARKS_REQUEST'
export const TEACHER_HOMEROOM_TERM_MARKS_SUCCESS =
  'TEACHER_HOMEROOM_TERM_MARKS_SUCCESS'
export const TEACHER_HOMEROOM_TERM_MARKS_FAIL =
  'TEACHER_HOMEROOM_TERM_MARKS_FAIL'

// teacher homeroom get term marks
export const TEACHER_HOMEROOM_ADD_TERM_MARK_REQUEST =
  'TEACHER_HOMEROOM_ADD_TERM_MARK_REQUEST'
export const TEACHER_HOMEROOM_ADD_TERM_MARK_SUCCESS =
  'TEACHER_HOMEROOM_ADD_TERM_MARK_SUCCESS'
export const TEACHER_HOMEROOM_ADD_TERM_MARK_FAIL =
  'TEACHER_HOMEROOM_ADD_TERM_MARK_FAIL'
export const TEACHER_HOMEROOM_ADD_TERM_MARK_DELETE =
  'TEACHER_HOMEROOM_ADD_TERM_MARK_DELETE'

// teacher homeroom get student subjects
export const TEACHER_HOMEROOM_STUDENT_SUBJECTS_REQUEST =
  'TEACHER_HOMEROOM_STUDENT_SUBJECTS_REQUEST'
export const TEACHER_HOMEROOM_STUDENT_SUBJECTS_SUCCESS =
  'TEACHER_HOMEROOM_STUDENT_SUBJECTS_SUCCESS'
export const TEACHER_HOMEROOM_STUDENT_SUBJECTS_FAIL =
  'TEACHER_HOMEROOM_STUDENT_SUBJECTS_FAIL'

// teacher homeroom get timetable
export const TEACHER_HOMEROOM_TIMETABLE_REQUEST =
  'TEACHER_HOMEROOM_TIMETABLE_REQUEST'
export const TEACHER_HOMEROOM_TIMETABLE_SUCCESS =
  'TEACHER_HOMEROOM_TIMETABLE_SUCCESS'
export const TEACHER_HOMEROOM_TIMETABLE_FAIL =
  'TEACHER_HOMEROOM_TIMETABLE_FAIL'

export const TEACHER_HOMEROOM_TIMETABLE_TEACHERS_REQUEST =
  'TEACHER_HOMEROOM_TIMETABLE_TEACHERS_REQUEST'
export const TEACHER_HOMEROOM_TIMETABLE_TEACHERS_SUCCESS =
  'TEACHER_HOMEROOM_TIMETABLE_TEACHERS_SUCCESS'
export const TEACHER_HOMEROOM_TIMETABLE_TEACHERS_FAIL =
  'TEACHER_HOMEROOM_TIMETABLE_TEACHERS_FAIL'

// get students
export const TEACHER_STUDENTS_REQUEST = 'TEACHER_STUDENTS_REQUEST'
export const TEACHER_STUDENTS_SUCCESS = 'TEACHER_STUDENTS_SUCCESS'
export const TEACHER_STUDENTS_FAIL = 'TEACHER_STUDENTS_FAIL'
export const TEACHER_STUDENTS_DELETE = 'TEACHER_STUDENTS_DELETE'

// get marks
export const TEACHER_SUBJECT_STUDENT_MARKS_REQUEST =
  'TEACHER_SUBJECT_STUDENT_MARKS_REQUEST'
export const TEACHER_SUBJECT_STUDENT_MARKS_SUCCESS =
  'TEACHER_SUBJECT_STUDENT_MARKS_SUCCESS'
export const TEACHER_SUBJECT_STUDENT_MARKS_FAIL =
  'TEACHER_SUBJECT_STUDENT_MARKS_FAIL'
export const TEACHER_SUBJECT_STUDENT_MARKS_DELETE =
  'TEACHER_SUBJECT_STUDENT_MARKS_DELETE'

// get truancys
export const TEACHER_SUBJECT_STUDENT_TRUANCYS_REQUEST =
  'TEACHER_SUBJECT_STUDENT_TRUANCYS_REQUEST'
export const TEACHER_SUBJECT_STUDENT_TRUANCYS_SUCCESS =
  'TEACHER_SUBJECT_STUDENT_TRUANCYS_SUCCESS'
export const TEACHER_SUBJECT_STUDENT_TRUANCYS_FAIL =
  'TEACHER_SUBJECT_STUDENT_TRUANCYS_FAIL'
export const TEACHER_SUBJECT_STUDENT_TRUANCYS_DELETE =
  'TEACHER_SUBJECT_STUDENT_TRUANCYS_DELETE'

export const TEACHER_FINAL_MARKS_REQUEST =
  'TEACHER_FINAL_MARKS_REQUEST'
export const TEACHER_FINAL_MARKS_SUCCESS =
  'TEACHER_FINAL_MARKS_SUCCESS'
export const TEACHER_FINAL_MARKS_FAIL = 'TEACHER_FINAL_MARKS_FAIL'

export const TEACHER_ADD_FINAL_MARK_REQUEST =
  'TEACHER_ADD_FINAL_MARK_REQUEST'
export const TEACHER_ADD_FINAL_MARK_SUCCESS =
  'TEACHER_ADD_FINAL_MARK_SUCCESS'
export const TEACHER_ADD_FINAL_MARK_FAIL =
  'TEACHER_ADD_FINAL_MARK_FAIL'
export const TEACHER_ADD_FINAL_MARK_DELETE =
  'TEACHER_ADD_FINAL_MARK_DELETE'

// add mark (and delete addMark)
export const TEACHER_ADD_MARK_REQUEST = 'TEACHER_ADD_MARK_REQUEST'
export const TEACHER_ADD_MARK_SUCCESS = 'TEACHER_ADD_MARK_SUCCESS'
export const TEACHER_ADD_MARK_FAIL = 'TEACHER_ADD_MARK_FAIL'
export const TEACHER_ADD_MARK_DELETE = 'TEACHER_ADD_MARK_DELETE'

// ad truancy (and delete addTruancy)
export const TEACHER_ADD_TRUANCY_REQUEST =
  'TEACHER_ADD_TRUANCY_REQUEST'
export const TEACHER_ADD_TRUANCY_SUCCESS =
  'TEACHER_ADD_TRUANCY_SUCCESS'
export const TEACHER_ADD_TRUANCY_FAIL = 'TEACHER_ADD_TRUANCY_FAIL'
export const TEACHER_ADD_TRUANCY_DELETE = 'TEACHER_ADD_TRUANCY_DELETE'

// motivate truancy (and delete motivateTruancy)
export const TEACHER_MOTIVATE_TRUANCY_REQUEST =
  'TEACHER_MOTIVATE_TRUANCY_REQUEST'
export const TEACHER_MOTIVATE_TRUANCY_SUCCESS =
  'TEACHER_MOTIVATE_TRUANCY_SUCCESS'
export const TEACHER_MOTIVATE_TRUANCY_FAIL =
  'TEACHER_MOTIVATE_TRUANCY_FAIL'
export const TEACHER_MOTIVATE_TRUANCY_DELETE =
  'TEACHER_MOTIVATE_TRUANCY_DELETE'

// add and get average marks (+ delete for each of them)
export const TEACHER_ADD_AVERAGE_REQUEST =
  'TEACHER_ADD_AVERAGE_REQUEST'
export const TEACHER_ADD_AVERAGE_SUCCESS =
  'TEACHER_ADD_AVERAGE_SUCCESS'
export const TEACHER_ADD_AVERAGE_FAIL = 'TEACHER_ADD_AVERAGE_FAIL'
export const TEACHER_ADD_AVERAGE_DELETE = 'TEACHER_ADD_AVERAGE_DELETE'

export const TEACHER_AVERAGE_MARKS_REQUEST =
  'TEACHER_AVERAGE_MARKS_REQUEST'
export const TEACHER_AVERAGE_MARKS_SUCCESS =
  'TEACHER_AVERAGE_MARKS_SUCCESS'
export const TEACHER_AVERAGE_MARKS_FAIL = 'TEACHER_AVERAGE_MARKS_FAIL'
export const TEACHER_AVERAGE_MARKS_DELETE =
  'TEACHER_AVERAGE_MARKS_DELETE'

export const TEACHER_TIMETABLE_REQUEST = 'TEACHER_TIMETABLE_REQUEST'
export const TEACHER_TIMETABLE_SUCCESS = 'TEACHER_TIMETABLE_SUCCESS'
export const TEACHER_TIMETABLE_FAIL = 'TEACHER_TIMETABLE_FAIL'

export const TEACHER_SCHOOL_REQUEST = 'TEACHER_SCHOOL_REQUEST'
export const TEACHER_SCHOOL_SUCCESS = 'TEACHER_SCHOOL_SUCCESS'
export const TEACHER_SCHOOL_FAIL = 'TEACHER_SCHOOL_FAIL'
